sudo: false
language: node_js
node_js:
  - '10'
install:
  - yarn
script:
  - yarn test
after_script:
  - npminstall codecov && codecov
env:
    global:
    - CODECOV_TOKEN="b1f05410-7844-4681-88bf-d49132edc931"