const Chinese = {
    Time: {
        END: '截止',
        ERROR: '错误',
        DAY: '% 天',
        HOUR: '% 时',
        MINS: '% 分',
        SEC: '% 秒',
    },
    PlayName: {
        K3AH: '安徽快三',
        K3BJ: '北京快三',
        K3FJ: '福建快三',
        K3GD: '广东快三',
        K3GS: '甘肃快3',
        K3GX: '广西快3',
        K3GZ: '贵州快3',
        K3HEB: '河北快3',
        K3HEN: '河南快3',
        K3HUB: '湖北快3',
        K3JS: '江苏快3',
        K3JX: '江西快3',
        K3NM: '内蒙快3',
        K3SH: '上海快3',
        K3XY: '幸运快3',
        K3TJ: '天津快3',
    },
    RouterTitle: {
        login: '登录',
        register: '注册',
        forget: '找回密码',
        home: '首页',
        cashMall: '现金商城',
        activeMall: '活动商城',
        scoreMall: '积分商城',
        userCenter: '我的账号',
        charge: '充值',
        withdrawal: '退货',
        set: '个人资料',
        auth: '实名认证',
        phone: '绑定新手机',
        updatePassWord: '修改密码',
        address: '收货地址',
        editAddress: '编辑收货地址',
        addAddress: '添加收货地址',
        bankCard: '我的银行卡',
        editBankCard: '编辑银行卡',
        addBankCard: '添加银行卡',
    },
    AC_MENU: {
        wallet: '我的钱包',
        set: '账号设置',
        address: '收货地址',
        bankCard: '银行卡',
        group: '我要开团',
        server: '联系客服',
        logout: '退出账号',
    },
    SETTING: {
        headPic: '头像',
        userName: '昵称',
        auth: '实名认证',
        phone: '手机号码',
        id: 'ID',
        updatePassWord: '修改密码',
    },
};

export default Chinese;
